//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDH.Repository {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDH.Repository.resources", typeof(resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Pizza Order.
        /// </summary>
        internal static string createpizzaorder {
            get {
                return ResourceManager.GetString("createpizzaorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELIVERED TO:.
        /// </summary>
        internal static string delto {
            get {
                return ResourceManager.GetString("delto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Fee:  .
        /// </summary>
        internal static string df {
            get {
                return ResourceManager.GetString("df", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  eg: Your orders are: pepperonli-too small and hawayan-Just right .
        /// </summary>
        internal static string eg1 {
            get {
                return ResourceManager.GetString("eg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Customer Name and Hit the [Enter Key] : .
        /// </summary>
        internal static string entercust {
            get {
                return ResourceManager.GetString("entercust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter House Number and Hit the [Enter Key] :  .
        /// </summary>
        internal static string enterloc {
            get {
                return ResourceManager.GetString("enterloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Order(s).
        /// </summary>
        internal static string enterord {
            get {
                return ResourceManager.GetString("enterord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Order ID and Hit the [Enter Key] :.
        /// </summary>
        internal static string enterorderdetails {
            get {
                return ResourceManager.GetString("enterorderdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\App_Data\\Pizza_Orders.json.
        /// </summary>
        internal static string fileid {
            get {
                return ResourceManager.GetString("fileid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To order please follow the entry format:.
        /// </summary>
        internal static string followformat1 {
            get {
                return ResourceManager.GetString("followformat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Format is:   2,1/3,2 .
        /// </summary>
        internal static string followformat2 {
            get {
                return ResourceManager.GetString("followformat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated Order ID: .
        /// </summary>
        internal static string genId {
            get {
                return ResourceManager.GetString("genId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza Delivery Hub.
        /// </summary>
        internal static string header {
            get {
                return ResourceManager.GetString("header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Hit the Enter Key When Done ].
        /// </summary>
        internal static string hitenter {
            get {
                return ResourceManager.GetString("hitenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House No.:     .
        /// </summary>
        internal static string hno {
            get {
                return ResourceManager.GetString("hno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:          .
        /// </summary>
        internal static string nm {
            get {
                return ResourceManager.GetString("nm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER DETAILS:.
        /// </summary>
        internal static string od {
            get {
                return ResourceManager.GetString("od", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID:      .
        /// </summary>
        internal static string oid {
            get {
                return ResourceManager.GetString("oid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Delivery.
        /// </summary>
        internal static string orderdelivery {
            get {
                return ResourceManager.GetString("orderdelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza:    .
        /// </summary>
        internal static string piz {
            get {
                return ResourceManager.GetString("piz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza Code: [1]All Chiz  [2]Pepperonli  [3]Hawayan.
        /// </summary>
        internal static string pizzanames {
            get {
                return ResourceManager.GetString("pizzanames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Code: [1]Too Small  [2]Just Right  [3]You might puke.
        /// </summary>
        internal static string pizzasizes {
            get {
                return ResourceManager.GetString("pizzasizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price:    .
        /// </summary>
        internal static string prc {
            get {
                return ResourceManager.GetString("prc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipts.
        /// </summary>
        internal static string receipts {
            get {
                return ResourceManager.GetString("receipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a number and Hit the [Enter Key] :.
        /// </summary>
        internal static string selectmenu {
            get {
                return ResourceManager.GetString("selectmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string subheader1 {
            get {
                return ResourceManager.GetString("subheader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:     .
        /// </summary>
        internal static string sz {
            get {
                return ResourceManager.GetString("sz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL PRICE:  .
        /// </summary>
        internal static string tot {
            get {
                return ResourceManager.GetString("tot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your orders are the following items:.
        /// </summary>
        internal static string yourordare {
            get {
                return ResourceManager.GetString("yourordare", resourceCulture);
            }
        }
    }
}
